name: Watermelon Action

on: [push, pull_request]

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
                  
            - name: Install Packages
              run: 'npm install'
            
            - name: Run Prettier
              run: 'npx prettier --write'
            
            - name: Run ESLint
              run: 'npx eslint --ext .js,.ts src'
